### ISSUE TITLE
cached_property is settable while property isn't

### ISSUE THREAD

**Issue by omerzimp** [pydanny/cached-property#12]
A property without `__set__` raises an `AttributeError`.
Cached property does not raise an `AttributeError` when being set.
Is that an implementation defect or intentional?
Shouldn't it behave like a read-only property behaves in terms of writeability?

**Comment by gsakkis** [comment]
On the one hand, it seems like an inadvertent side-effect of the implementation. `cached_property` is currently a [non-data descriptor](https://docs.python.org/2/howto/descriptor.html) and as such it may be overridden by instance dictionaries. If a `__set__` method is added, it becomes a data descriptor and data descriptors always override instance dictionaries. Still, it is possible to change the implementation so that it works correctly even as data descriptor like the latest [`cached_property_with_ttl`](https://github.com/pydanny/cached-property/blob/master/cached_property.py#L56).

On the other hand, one could argue that being settable is more of a feature than a bug. I think the major characteristic of cached properties is that they don't incur a (potentially expensive) computation *once the value of the property is available*. Whether the value became available implicitly through an initial `get` operation or explicitly through a `set` is not relevant.

**Comment by carterbox** [comment]
I agree with @gsakkis. Anytime there is a faster way to update the cached_property using additional information you want the property to be setable.

Example: Calculating the center of a graph. (graph.center)
_Default:_ averaging the locations of all the points O(n)
_Added a new point:_ use a weighted average of the current center and the new point O(1)

The default case is necessary if you are going to making arbitrary transformations to the graph, but for special changes to the graph like adding a single new point, you want to be able to set the property from outside the center method.

**Comment by pydanny** [comment]
I'm worried that fixing this might break numerous usages of `cached-property`. What might be a bug by us might be considered a feature by others. Some thoughts:

1. Should we continue to allow this behavior?
2. If we deny this behavior, should we also allow the old behavior as well?
3. If we allow the old behavior as well, how do we toggle the difference in behavior?
4. If we are to fix/correct this "bug", it would predicate the release of 2.0

**Comment by pydanny** [comment]
This is a feature of the `cached-property` decorator, not a bug or question.
